### ISSUE TITLE
add 2 new rules

### ISSUE THREAD

**Issue by larshp** [FreHu/abaplint-clean-code#6]
https://github.com/abaplint/abaplint/blob/master/src/rules/prefer_returning_to_exporting.ts

and 

https://github.com/abaplint/abaplint/blob/master/src/rules/whitespace/keep_single_parameter_on_one_line.ts

**Comment by FreHu** [comment]
Added in https://github.com/FreHu/abaplint-clean-code/commit/1e7d61e3581c6f7b67d43e76181c83048cc0ab88. There's many more new rules actually, I'll get to them at some point.
